import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { FIR } from "../types";

export const generateFIRPDF = (fir: FIR) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(41, 128, 185);
    doc.text("FIR Report", 105, 20, { align: "center" });

    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text("Generated by FIR Automation System", 105, 28, { align: "center" });

    doc.setLineWidth(0.5);
    doc.line(20, 35, 190, 35);

    doc.setFontSize(12);
    doc.setTextColor(0);

    const startY = 45;

    doc.setFont("helvetica", "bold");
    doc.text(`FIR ID: ${fir.filing_number || fir._id}`, 20, startY);

    doc.setFont("helvetica", "normal");
    doc.text(
        `Date Filed: ${new Date(fir.submission_date).toLocaleDateString()}`,
        140,
        startY
    );

    doc.text(
        `Status: ${fir.status.replace("_", " ").toUpperCase()}`,
        20,
        startY + 10
    );

    doc.text(`Station ID: ${fir.station_id}`, 140, startY + 10);

    autoTable(doc, {
        startY: startY + 20,
        head: [["Complainant Details", ""]],
        body: [
            ["Name", fir.complainant_name || "N/A"],
            ["Phone", fir.complainant_phone || "N/A"],
            ["Aadhar", fir.complainant_aadhar || "N/A"],
            ["Email", fir.complainant_email || "N/A"],
        ],
        theme: "grid",
        headStyles: { fillColor: [41, 128, 185] },
    });

    autoTable(doc, {
        startY: (d