import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { FIR } from "../types";

export const generateFIRPDF = (fir: FIR) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(41, 128, 185);
    doc.text("FIR Report", 105, 20, { align: "center" });

    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text("Generated by FIR Automation System", 105, 28, { align: "center" });

    // Draw Line
    doc.setLineWidth(0.5);
    doc.line(20, 35, 190, 35);

    // FIR Details
    doc.setFontSize(12);
    doc.setTextColor(0);

    const startY = 45;

    doc.setFont("helvetica", "bold");
    doc.text(`FIR ID: ${fir._id}`, 20, startY);

    doc.setFont("helvetica", "normal");
    doc.text(`Date Filed: ${new Date(fir.submission_date).toLocaleDateString()}`, 140, startY);

    doc.text(`Status: ${fir.status.toUpperCase()}`, 20, startY + 10);
    doc.text(`Station ID: ${fir.station_id}`, 140, startY + 10);

    // Complainant Details Table
    autoTable(doc, {
        startY: startY + 20,
        head: [["Complainant Details", ""]],
        body: [
            ["Name", fir.complainant_name || "N/A"],
            ["Phone", fir.complainant_phone || "N/A"],
            ["Aadhar", fir.complainant_aadhar || "N/A"],
            ["Email", fir.complainant_email || "N/A"],
        ],
        theme: "grid",
        headStyles: { fillColor: [41, 128, 185] },
    });

    // Incident Details Table
    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 10,
        head: [["Incident Details", ""]],
        body: [
            ["Location", fir.location || "N/A"],
            ["Date & Time", `${fir.incident_date} at ${fir.incident_time}`],
        ],
        theme: "grid",
        headStyles: { fillColor: [41, 128, 185] },
    });

    // Description
    // Incident Description Table
    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 10,
        head: [["Incident Description"]],
        body: [[fir.original_text]],
        theme: "grid",
        headStyles: { fillColor: [41, 128, 185] },
        styles: { cellWidth: 'auto', overflow: 'linebreak' }, // Ensure wrapping
    });

    // Police Notes (If available)
    if (fir.police_notes) {
        autoTable(doc, {
            startY: (doc as any).lastAutoTable.finalY + 10,
            head: [["Police Notes"]],
            body: [[fir.police_notes]],
            theme: "grid",
            headStyles: { fillColor: [41, 128, 185] },
            styles: { cellWidth: 'auto', overflow: 'linebreak' },
        });
    }

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(10);
        doc.text('Page ' + String(i) + ' of ' + String(pageCount), 190, 280, { align: "right" });
        doc.text(`Downloaded on: ${new Date().toLocaleString()}`, 20, 280);
    }

    // Save the PDF
    doc.save(`FIR_Report_${fir._id}.pdf`);
};
