import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { FIR } from "../types";

export const generateFIRPDF = (fir: FIR) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(41, 128, 185);
    doc.text("FIR Report", 105, 20, { align: "center" });

    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text("Generated by FIR Automation System", 105, 28, { align: "center" });

    doc.setLineWidth(0.5);
    doc.line(20, 35, 190, 35);

    doc.setFontSize(12);
    doc.setTextColor(0);

    const startY = 45;

    doc.setFont("helvetica", "bold");
    doc.text(`FIR ID: ${fir.filing_number || fir._id}`, 20, startY);

    doc.setFont("helvetica", "normal");
    doc.text(
        `Date Filed: ${new Date(fir.submission_date).toLocaleDateString()}`,
        140,
        startY
    );

    doc.text(
        `Status: ${fir.status.replace("_", " ").toUpperCase()}`,
        20,
        startY + 10
    );

    doc.text(`Station ID: ${fir.station_id}`, 140, startY + 10);

    autoTable(doc, {
        startY: startY + 20,
        head: [["Complainant Details", ""]],
        body: [
            ["Name", fir.complainant_name || "N/A"],
            ["Phone", fir.complainant_phone || "N/A"],
            ["Aadhar", fir.complainant_aadhar || "N/A"],
            ["Email", fir.complainant_email || "N/A"],
        ],
        theme: "grid",
        headStyles: { fillColor: [41, 128, 185] },
    });

    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 10,
        head: [["Incident Details", ""]],
        body: [
            ["Date", new Date(fir.incident_date).toLocaleDateString()],
            ["Time", fir.incident_time],
            ["Location", fir.location],
        ],
        theme: "grid",
        headStyles: { fillColor: [41, 128, 185] },
    });

    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 10,
        head: [["FIR Description"]],
        body: [[fir.original_text || "N/A"]],
        theme: "grid",
        headStyles: { fillColor: [41, 128, 185] },
    });

    if (fir.police_notes) {
        autoTable(doc, {
            startY: (doc as any).lastAutoTable.finalY + 10,
            head: [["Police Notes"]],
            body: [[fir.police_notes]],
            theme: "grid",
            headStyles: { fillColor: [41, 128, 185] },
        });
    }

    if (fir.applicable_sections && fir.applicable_sections.length > 0) {
        autoTable(doc, {
            startY: (doc as any).lastAutoTable.finalY + 10,
            head: [["Applicable Sections"]],
            body: [[fir.applicable_sections.join(", ")]],
            theme: "grid",
            headStyles: { fillColor: [41, 128, 185] },
        });
    }

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text(
            `Page ${i} of ${pageCount}`,
            105,
            doc.internal.pageSize.height - 10,
            { align: "center" }
        );
    }

    doc.save(`FIR_${fir.filing_number || fir._id}.pdf`);
};
